---
title: "FinistR : bootcamp R à Roscoff"
date: "du 23 au 27 août 2021"
output: 
  html_document:
   toc: true
   toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, cache = TRUE)
library(tidyverse)
```

## Où ? Quand ?

L'atelier Finist'R 2021 -- ou *bootcamp R* du groupe  [State Of The R](https://stateofther.github.io/)  se tiendra à la [station biologique de Roscoff](http://www.sb-roscoff.fr/) du **23 au 27 août 2021**.

<iframe src="https://www.google.com/maps/embed?pb=!1m17!1m11!1m3!1d863.0230997053625!2d-3.987533179360306!3d48.72647094495075!2m2!1f0!2f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4813e153cbdda967%3A0x6cd2956ee2bb8cfb!2sStation+Biologique+de+Roscoff!5e1!3m2!1sfr!2sfr!4v1557410926937!5m2!1sfr!2sfr" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>



Il s'agit de la cinquième édition de l'atelier Finist'R. Cet atelier réunit annuellement un groupe de chercheurs, ingénieurs, doctorants, tous utilisateurs avancés de `R` et dévelopeurs de paquets pour explorer les dernières fonctionalités du logiciel et les nouvelles pratiques de développement. A l'issu de l'atelier le collectif produit une synthèse de cette veille logiciel de manière à progresser collectivement dans l'utilisation du logiciel mais surtout dans la production d'outils statistiques à destination de la communauté.

La restitution se fait sous forme de site web. Le site de l'édition 2021 [sera disponible ici](https://stateofther.github.io/finistR2021/index.html)

## Participants
Eric Adjakossa,  Julie Aubert,  Pierre Barbillon, Saint-Clair Chabert, Julien Chiquet, Sophie Donnet, Nicolas Enjalbert Courrech, Marie-Pierre Etienne, José Garcia-Gomez, Pierre Gloaguen,  Gabriel Lang, Tam Le Minh, Gaspar Massiot, Pierre Navaro, Rémi Patin, Isabelle Sanchez.







